name: Deployment workflow for casinoonlinejp

on:
  push:
    branches: 
    - 'develop'
  pull_request:
    branches:
    - 'develop'
jobs:
  activate-github-runner:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    permissions:
      id-token: write
      contents: read
    outputs:
      gitrunner_vm_id: ${{ steps.runner-label.outputs.vm_id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Check identity
        id: validate
        run: |
          aws sts get-caller-identity
      - name: Generate Runner label
        id: runner-label
        run: |
          task_vm_id=$(uuidgen)
          echo "::set-output name=vm_id::$task_vm_id"
          echo "VM ID generated $task_vm_id"
      - name: Identify applicable configuration
        id: task-config
        run: |
            echo "::set-output name=NET_CONFIG::--network-configuration 'awsvpcConfiguration={subnets=[${{ secrets.SUBNET }}],securityGroups=[${{ secrets.SECURITY_GROUP }}],assignPublicIp=ENABLED}'"
            echo "::set-output name=TASK_DEF_NAME::${{ github.event.inputs.Env }}_fg_git_runner"
        shell: bash
      - name: Start ECS Task for Github self-hosted runner
        id: create-task
        run: >
          aws ecs run-task 
          --cluster "${{ github.event.inputs.Env }}-git-runner" --launch-type "FARGATE" 
          --task-definition "${{ steps.task-config.outputs.TASK_DEF_NAME }}" 
          --overrides '{"containerOverrides": [{"name": "infra-aws-core",
          "environment" : [{"name": "RUNNER_NAME", "value": "${{ steps.task-config.outputs.TASK_DEF_NAME }}-${{ steps.runner-label.outputs.vm_id }}"},
          {"name": "RUNNER_LABELS", "value": "${{ steps.runner-label.outputs.vm_id }}"},
          {"name": "GITHUB_PAT", "value": "${{ secrets.RUNNER_PAT }}"}
          ]}]}'
          ${{ steps.task-config.outputs.NET_CONFIG }}
  deployment:
    needs: [activate-github-runner]
    runs-on: ['self-hosted', "${{ needs.activate-github-runner.outputs.gitrunner_vm_id }}"]
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Set environment for branch
      run: |
        if [[ $GITHUB_BASE_REF == 'develop' ]]; then
            echo "working_dir_wp-site=/var/www/html/casinoonlinejp-dev.catena.media/wp-site" >> "$GITHUB_ENV"
            echo "efs_name=fs-009ea642a4ee5d5be.efs.ap-east-1.amazonaws.com" >> "$GITHUB_ENV"
            echo "environment=development" >> "$GITHUB_ENV"
        else
            echo "working_dir_wp-site=/var/www/html/casinoonlinejp-stg.catena.media/wp-site" >> "$GITHUB_ENV"
            echo "efs_name=fs-xxxxx.efs.ap-east-1.amazonaws.com" >> "$GITHUB_ENV"
            echo "environment=staging" >> "$GITHUB_ENV"
        fi
    - name: Checkout
      uses: actions/checkout@v3
    - name: casinoonlinejp-dev deployment
      if:  github.base_ref == 'develop'
      run : | 
        echo "Running pipeline on Bastion AWS APAC Dev"
    - name: casinoonlinejp-stg deployment
      if:  github.base_ref == 'staging'
      run : | 
        echo "Running pipeline on Bastion AWS APAC Stg"
    - name: Check mount status and Mount EFS
      uses: ./.github/workflows/mount-efs
      with:
        efs_name: ${{env.efs_name}}
    - name: Pre deployment steps
      uses: ./.github/workflows/pre-deployment
      with:
        working_dir_wp-site: ${{env.working_dir_wp-site}}
    - name: Git Checkout
      uses: ./.github/workflows/deploy
      with:
        working_dir_wp-site: ${{env.working_dir_wp-site}}
    - name: Post deployment steps
      uses: ./.github/workflows/post-deployment
      with:
        working_dir_wp-site: ${{env.working_dir_wp-site}}
    - name: Unmount file system
      uses: ./.github/workflows/unmount-efs
    - name: Cleanup workspace
      uses: ./.github/workflows/cleanup
